### ISSUE TITLE
File "scripts/demo.py", line 7, in <module>

### ISSUE THREAD

**Issue by mem0rz** [imcaspar/gpt2-ml#134]
Traceback (most recent call last):
File "scripts/demo.py", line 7, in
import tensorflow.compat.v1 as tf
File "/usr/local/lib/python3.7/dist-packages/tensorflow/init.py", line 102, in
from tensorflow_core import *
File "/usr/local/lib/python3.7/dist-packages/tensorflow_core/init.py", line 28, in
from tensorflow.python import pywrap_tensorflow # pylint: disable=unused-import
File "", line 1019, in _handle_fromlist
File "/usr/local/lib/python3.7/dist-packages/tensorflow/init.py", line 50, in getattr
module = self._load()
File "/usr/local/lib/python3.7/dist-packages/tensorflow/init.py", line 44, in _load
module = _importlib.import_module(self.name)
File "/usr/lib/python3.7/importlib/init.py", line 127, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "/usr/local/lib/python3.7/dist-packages/tensorflow_core/python/init.py", line 52, in
from tensorflow.core.framework.graph_pb2 import *
File "/usr/local/lib/python3.7/dist-packages/tensorflow_core/core/framework/graph_pb2.py", line 7, in
from google.protobuf import descriptor as _descriptor
File "/usr/local/lib/python3.7/dist-packages/google/protobuf/descriptor.py", line 40, in
from google.protobuf.internal import api_implementation
File "/usr/local/lib/python3.7/dist-packages/google/protobuf/internal/api_implementation.py", line 104, in
from google.protobuf.pyext import _message
TypeError: bases must be types

**Comment by zxkmm** [comment]
Pls let us know your enviroment.

**Comment by mem0rz** [comment]
> Pls let us know your enviroment.

Google colab

**Comment by zxkmm** [comment]
> Google colab

@mem0rz  Pls use this fork. The bug you have should be fixed in this fork.

https://github.com/zxkmm/gpt2-ml-fixed

**Comment by mem0rz** [comment]
> > Google colab
> 
> @mem0rz Pls use this fork. The bug you have should be fixed in this fork.
> 
> https://github.com/zxkmm/gpt2-ml-fixed

Actually , this is the fork which I use.

**Comment by zxkmm** [comment]
> Actually , this is the fork which I use.
Thank you! I’ll merge it.
