### ISSUE TITLE
AttributeError: module 'tensorflow_core._api.v2.train' has no attribute 'Optimizer'[Discussion] your question

### ISSUE THREAD

**Issue by jiujiangxueyuan** [imcaspar/gpt2-ml#58]
When I try this model in colab ,it reported these:
Traceback (most recent call last):
  File "scripts/interactive_conditional_samples.py", line 10, in <module>
    from train.modeling import GroverModel, GroverConfig, sample
  File "/content/gdrive/Shared drives/myDrive/Download/gpt2-ml/train/modeling.py", line 23, in <module>
    from train import optimization_adafactor
  File "/content/gdrive/Shared drives/myDrive/Download/gpt2-ml/train/optimization_adafactor.py", line 88, in <module>
    class AdaFactorOptimizer(tf.train.Optimizer):
AttributeError: module 'tensorflow_core._api.v2.train' has no attribute 'Optimizer'

**Comment by artxtech** [comment]
感觉是tf版本的问题 我强制88行改了也不行

**Comment by imcaspar** [comment]
colab 的 tf version 指定看起来有些问题
